// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_entries_slug_add from "./routes/api/entries/[slug]/add.ts";
import * as $api_sesh_slug_auth from "./routes/api/sesh/[slug]/auth.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/entries/[slug]/add.ts": $api_entries_slug_add,
    "./routes/api/sesh/[slug]/auth.ts": $api_sesh_slug_auth,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
