// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_entries_slug_add from "./routes/api/entries/[slug]/add.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_sesh_slug_auth from "./routes/api/sesh/[slug]/auth.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $partials_login from "./routes/partials/login.tsx";
import * as $Counter from "./islands/Counter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/entries/[slug]/add.ts": $api_entries_slug_add,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/sesh/[slug]/auth.ts": $api_sesh_slug_auth,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/partials/login.tsx": $partials_login,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
